"""Updated models

Revision ID: eaa1731a41d3
Revises: 
Create Date: 2024-08-02 15:47:58.113803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa1731a41d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fear_greed_bot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_configuration',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cvi', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('alerts', sa.Column('headline', sa.Text(), nullable=True))
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'services',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="services::json")
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'services',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_column('alerts', 'headline')
    op.drop_table('user_configuration')
    op.drop_table('fear_greed_bot')
    # ### end Alembic commands ###
