"""Add fear_greed_bot table

Revision ID: f89bde3429a2
Revises: eaa1731a41d3
Create Date: 2024-08-03 13:22:09.303925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89bde3429a2'
down_revision: Union[str, None] = 'eaa1731a41d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fear_greed_bot', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fear_greed_bot', type_='unique')
    # ### end Alembic commands ###
